---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kbmvscon/staging_html/
    - /usr/bin/test -f /home/kbmvscon/config/env/.env.staging || (echo "Missing .env.staging" && exit 1)
    - /usr/bin/rsync -az --delete --exclude ".git" --exclude ".cpanel.yml" ./ $DEPLOYPATH
    - /usr/local/cpanel/bin/ea_php_cli -d opcache.enable_cli=1 -r 'opcache_reset();'
